name: Train and Register Model

on:
  push:
    branches:
      - main

jobs:
  train-test-register:
    # Use self-hosted runner instead of ubuntu-latest
    runs-on: self-hosted  # Specify 'self-hosted' for local runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token

      # Step 2: Set up Python
      #- name: Set up Python
      #  uses: actions/setup-python@v2
      #  with:
      #    python-version: '3.10.12'
          
      # Step 3: Install dependencies
      #- name: Install dependencies
      #  run: |
      #    pip install -r requirements.txt

      # Step 4: Ensure data.csv is available
      - name: Ensure dataset exists
        run: |
          if [ ! -f data/data.csv ]; then
            echo "Error: data.csv not found!" 
            exit 1
          fi

      # Step 5: Train the model
      - name: Train the model
        run: python model/train.py

      # Step 6: Test the model
      - name: Test the model
        run: python model/test.py

      # Step 7: Register the model (if passed the test)
      - name: Register the model (if passed test)
        run: python mlflow/register.py
